### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by Marie-Joseph** [chux0519/runcat-tray#2]
Since there is no license in the repository, this project is technically proprietary. However, given that it is hosted publicly on GitHub, and is meant for a Linux-based operating system, I assume this is not the intended licensing strategy. Please clarify the license as I would like to fork this primarily for personal use (specifically from the code as of November 1st), but I also want to respect the creator's wishes.

**Comment by chux0519** [comment]
Hey, thank you for mention the license issue, I think the two-clause BSD license is good for the code, and as for all the resources from internet(those icons), I think should respect the original author.
Also I've merged the PR you created two days ago, didn't notice those bug, thank you and well done!

**Comment by Marie-Joseph** [comment]
Thank you!
